# Generated by Django 4.2.3 on 2023-08-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0002_alter_ciudad_cod_deptdane'),
        ('clientes', '__first__'),
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachociudad',
            name='cod_CiudDANE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CiudadDespacho', to='ciudades.ciudad'),
        ),
        migrations.AlterField(
            model_name='despachociudad',
            name='id_guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guiaDespacho', to='guia.guiadespacho', verbose_name='Guia'),
        ),
        migrations.AlterField(
            model_name='guiacliente',
            name='id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienteGuia', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='guiacliente',
            name='id_guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guiaCliente', to='guia.guiadespacho', verbose_name='Guia'),
        ),
        migrations.AlterField(
            model_name='guiaestado',
            name='id_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadoGuia', to='guia.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='guiaestado',
            name='id_guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guiaEstado', to='guia.guiadespacho', verbose_name='Guía'),
        ),
        migrations.AlterField(
            model_name='guiaservicio',
            name='id_guia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guiaServicio', to='guia.guiadespacho', verbose_name='Guia'),
        ),
        migrations.AlterField(
            model_name='guiaservicio',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServicioGuia', to='guia.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='liquidador',
            name='cod_CiudDANE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudadLiquidador', to='ciudades.ciudad'),
        ),
        migrations.AlterField(
            model_name='liquidador',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicioLiquidador', to='guia.servicio', verbose_name='Servicio'),
        ),
    ]
