# Generated by Django 4.2.4 on 2023-08-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_DeptDANE', models.CharField(max_length=3, verbose_name='CódDepartamento')),
                ('nombre_departamento', models.CharField(max_length=60, verbose_name='NomDepartamento')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_CiudDANE', models.CharField(max_length=4, verbose_name='CódCiudad')),
                ('nombre_ciudad', models.CharField(max_length=60, verbose_name='Ciudad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('cod_DeptDANE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadDpto', to='ciudades.departamento', verbose_name='CódDepartamento')),
            ],
        ),
    ]
