# Generated by Django 4.2.3 on 2023-08-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='cod_DeptDANE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudadDpto', to='ciudades.departamento', verbose_name='CódDepartamento'),
        ),
    ]
