# Generated by Django 4.2.3 on 2023-08-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0002_alter_ciudad_cod_deptdane'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pto_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioPVenta', to='usuarios.puntoventa'),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='cod_CiudDANE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CiudadPVenta', to='ciudades.ciudad'),
        ),
    ]
