# Generated by Django 4.2.3 on 2023-09-06 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=45, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.CharField(max_length=45, verbose_name='Céd Cliente')),
                ('nombre_uno', models.CharField(max_length=60, verbose_name='Pri Nom Cliente')),
                ('nombre_dos', models.CharField(max_length=60, verbose_name='Seg Nom cliente')),
                ('apellido_uno', models.CharField(max_length=60, verbose_name='Pri Ape Cliente')),
                ('apellido_dos', models.CharField(max_length=60, verbose_name='Seg Ape Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_cliente', models.CharField(max_length=15, verbose_name='Número celular cliente')),
                ('direccion_cliente', models.CharField(max_length=100, verbose_name='Dirección del cliente')),
                ('personeria', models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Persona Jurídica', 'Persona Jurídica')], default='Persona Natural', max_length=45, verbose_name='Personería')),
                ('tipo_cliente', models.CharField(choices=[('Remitente', 'Remitente'), ('Destinatario', 'Destinatario')], default='Remitente', max_length=45, verbose_name='Tipo de cliente')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('cod_CiudDANE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienteCiudad', to='ciudades.ciudad')),
                ('id_juridica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerJuridica', to='clientes.personajuridica', verbose_name='Id persona jurídica')),
                ('id_natural', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerNatural', to='clientes.personanatural', verbose_name='Id persona natural')),
            ],
        ),
    ]
